Bump up cayman_helm to fix errors
Cayman_helm generates errors for the latest windows
manifests since it does not set the correct LDFLAGS.
```
Error: chart requires kubeVersion: >= 1.22.0-0 which is incompatible with Kubernetes v1.20.0
```

The fix in cayman_helm is at
https://gitlab.eng.vmware.com/core-build/cayman_helm/-/commit/bcc709d6441aa2fbd3b9abaa9f8e56a68a96f3b0

Signed-off-by: Xu Liu <xu.liu@broadcom.com>